---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow-kafka-zookeeper"
  namespace: {{ .Values.processingNamespace | default .Release.Namespace }}
specs:
  - endpointSelector:
      matchLabels:
        k8s:app.kubernetes.io/name: zookeeper
    ingress:
    - fromEndpoints:
      - matchLabels:
          k8s:selector.cilium.rbkmoney/release: kafka 
      toPorts:
      - ports:
        - port: "2181"
          protocol: TCP
  - endpointSelector:
      matchLabels:
        k8s:selector.cilium.rbkmoney/release: kafka
    egress:
    - toEndpoints:
      - matchLabels:
          k8s:app.kubernetes.io/name: zookeeper
      toPorts:
      - ports:
        - port: "2181"
          protocol: TCP
